### PR TITLE
Backend client

### PR DESCRIPTION
**Pull request by gnahum12345**
## Summary: 
- Fixed models to be coherent with ParseServer. 
- Created `PostManager` to get and fetch posts to `ParseServer`. 
- Created `LogIn/SignUp` pages respectively. (probably need to make it nicer?)
- Changed MyRecyclerViewAdapter to accept `Post` instead of Bitmaps and then can display posts retrieved from db. 
- Added 'post' functionality to db after the user clicks "post" when creating a post. 
   - Need to add a way to list all users they want to talk to.

### CODE REVIEW

**Comment by gnahum12345** [comment]
Sorry this is kinda a big pull request... I didn't realize it would be this big.

**Comment by gnahum12345** [comment]
[video](https://drive.google.com/file/d/1GfUcsOxFNC6r-lOnpp46A4TxtSY1O1_o/view?usp=sharing)

**Comment by gnahum12345** [comment]
I kept the style of masters branch.

**Review by AlphaZach — APPROVED** [review]
looks good

**Pull request merged**
